### ISSUE TITLE
Porque no agragas un nuevo archivo file4.txt

### ISSUE THREAD

**Issue by lugounidep** [lugouadec/Test01#2]
deberias crear un archivo file4.txt para poder solucionar el problemas ... !

**Comment by lugouadec** [comment]
muy bien lo pensare y si lo considero necesario de ara el cambio .

Saludos !!

**Comment by lugounidep** [comment]
> muy bien lo pensare y si lo considero necesario de ara el cambio .
> 
> Saludos !!

Muchas Gracias por tomarnos en cuenta !!!

**Comment by lugouadec** [comment]
> > muy bien lo pensare y si lo considero necesario de ara el cambio .
> > Saludos !!
> 
> Muchas Gracias por tomarnos en cuenta !!!

Muchas Gracias !!!

**Comment by lugouadec** [comment]
Cerrare el Issue !!!

**Comment by lugounidep** [comment]
Muchas Gracias !!!
